---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-mcp
  labels:
    app: consul-mcp
spec:
  selector:
    matchLabels:
      app: consul-mcp
  replicas: 1
  template:
    metadata:
      labels:
        app: consul-mcp
    spec:
      containers:
        - name: consul-mcp
          image: zhaohuabing/consul-mcp
          env:
            - name: listeningAddress
              value: "0.0.0.0:1109"
            - name: consulAddress
              value: "consul:8500"
          ports:
            - containerPort: 1109
---
apiVersion: v1
kind: Service
metadata:
  name: consul-mcp
spec:
  selector:
    app: consul-mcp
  ports:
    - name: tcp
      port: 1109
      protocol: TCP
      targetPort: 1109